import { DETAILS } from './details.js'

// Eras label periods for the scrubber readout and entry chips. Overlap allowed.
export const ERAS = [
  { id: 'ori', name: 'Origins', start: -2000, end: -600 },
  { id: 'gre', name: 'The Greek Miracle', start: -600, end: 415 },
  { id: 'eas', name: 'The Eastern Millennium', start: 200, end: 1450 },
  { id: 'isl', name: 'The House of Wisdom', start: 780, end: 1300 },
  { id: 'ren', name: 'Renaissance', start: 1170, end: 1640 },
  { id: 'rev', name: 'The Scientific Revolution', start: 1600, end: 1730 },
  { id: 'enl', name: 'The Age of Euler', start: 1700, end: 1830 },
  { id: 'rig', name: 'The Age of Rigor', start: 1800, end: 1900 },
  { id: 'fou', name: 'Crisis & Foundations', start: 1880, end: 1940 },
  { id: 'mod', name: 'The Modern Age', start: 1930, end: 2026 },
]

// The roster. Dates BCE are negative; several ancient dates are traditional
// approximations. `school` is the figure's home ground shown as a chip;
// `influences` are the load-bearing debts only — every pair is annotated in
// edges.js and drawn as an arc on the globe.
const ROSTER = [
  // ---- Origins ----
  { id: 'ahmes', name: 'Ahmes', born: -1620, died: -1550, era: 'ori', school: 'Egyptian reckoning', tradition: 'egypt',
    blurb: 'The scribe of the Rhind papyrus and the first mathematician whose name we know — a copyist, he tells us, of writings two centuries older still. Fractions, areas, and the pyramid problems of a working river civilization.',
    line: 'Accurate reckoning: the entrance into knowledge of all existing things.', influences: [] },

  // ---- The Greek Miracle ----
  { id: 'thales', name: 'Thales', born: -624, died: -546, era: 'gre', school: 'Ionian geometry', tradition: 'greek',
    blurb: 'Brought geometry home from Egypt and did something no scribe had done: proved a statement true of every circle at once. With him mathematics stops being a bag of recipes and becomes a claim about all possible cases.',
    line: 'The pyramid is measured by its shadow.', influences: ['ahmes'] },
  { id: 'pythagoras', name: 'Pythagoras', born: -570, died: -495, era: 'gre', school: 'Pythagorean', tradition: 'greek',
    blurb: 'Founded a brotherhood convinced that number is the substance of reality — harmony as ratio, the cosmos as ordered proportion. The faith that mathematics underwrites the world begins as literal religion.',
    line: 'All is number.', influences: ['thales'] },
  { id: 'zeno', name: 'Zeno of Elea', born: -490, died: -430, era: 'gre', school: 'Eleatic', tradition: 'greek',
    blurb: 'Armed four paradoxes proving motion impossible — Achilles never catches the tortoise, the arrow never moves. Mathematics spent two thousand years building the machinery (limits, convergence, the continuum) to answer him.',
    line: 'Achilles never catches the tortoise.', influences: [] },
  { id: 'euclid', name: 'Euclid', born: -325, died: -265, era: 'gre', school: 'Alexandria', tradition: 'greek',
    blurb: 'Compressed all known geometry into thirteen books deduced from five postulates — the Elements, the most reprinted secular book in history. The axiomatic method: certainty by architecture rather than authority.',
    line: 'There is no royal road to geometry.', influences: ['pythagoras'] },
  { id: 'archimedes', name: 'Archimedes', born: -287, died: -212, era: 'gre', school: 'Syracuse', tradition: 'greek',
    blurb: 'Weighed parabolas, exhausted circles with polygons, and computed with infinitesimals eighteen centuries before calculus dared to. Antiquity’s greatest mathematician, killed mid-diagram by a Roman soldier.',
    line: 'Give me a place to stand and I will move the Earth.', influences: ['euclid'] },
  { id: 'eratosthenes', name: 'Eratosthenes', born: -276, died: -194, era: 'gre', school: 'Alexandria', tradition: 'greek',
    blurb: 'Librarian of Alexandria who measured the circumference of the Earth with a well, a stick, and a shadow — and sieved the primes while he was at it. Measurement as audacity.',
    line: 'The Earth can be measured with a stick and a shadow.', influences: ['euclid'] },
  { id: 'hypatia', name: 'Hypatia', born: 355, died: 415, era: 'gre', school: 'Alexandria', tradition: 'greek',
    blurb: 'The last great teacher of the Alexandrian tradition — editor of the Elements’ lineage, commentator on the conics and on Diophantus — murdered by a mob as the ancient world closed. Where the Greek chapter ends.',
    line: 'The heavens obey geometry.', influences: ['euclid'] },

  // ---- The Eastern Millennium ----
  { id: 'liuhui', name: 'Liu Hui', born: 225, died: 295, era: 'eas', school: 'Nine Chapters', tradition: 'china',
    blurb: 'China’s great commentator, who did not just state the rules of the Nine Chapters but proved them — and closed in on π by cutting a 3,072-sided polygon, reasoning that the finer the cut, the smaller the loss.',
    line: 'The finer the cutting, the smaller the loss.', influences: [] },
  { id: 'aryabhata', name: 'Aryabhata', born: 476, died: 550, era: 'eas', school: 'Kusumapura', tradition: 'india',
    blurb: 'At twenty-three wrote the Aryabhatiya: sine tables, place-value arithmetic in verse, π to four places, and the claim — thirteen centuries early — that the Earth rotates and the stars only seem to move.',
    line: 'The Earth turns; the stars stand still.', influences: [] },
  { id: 'brahmagupta', name: 'Brahmagupta', born: 598, died: 668, era: 'eas', school: 'Ujjain school', tradition: 'india',
    blurb: 'First to treat zero as a number with rules of its own — and negative numbers as debts you can calculate with. Arithmetic as we know it, complete with its hardest question: what is division by zero?',
    line: 'Zero is what remains when a number is taken from itself.', influences: ['aryabhata'] },
  { id: 'madhava', name: 'Madhava', born: 1340, died: 1425, era: 'eas', school: 'Kerala school', tradition: 'india',
    blurb: 'In Kerala, two and a half centuries before Newton, expanded π and the sine as infinite series — summing the unending. The Kerala school he founded carried calculus’s core idea while Europe slept on it.',
    line: 'The circle yields to an endless sum.', influences: ['brahmagupta'] },

  // ---- The House of Wisdom ----
  { id: 'alkhwarizmi', name: 'al-Khwarizmi', born: 780, died: 850, era: 'isl', school: 'House of Wisdom', tradition: 'islam',
    blurb: 'In Baghdad wrote the book of al-jabr — restoration — that named algebra, and the arithmetic text that carried Indian numerals west. His own name, Latinized, became the word algorithm: procedure as an object of study.',
    line: 'Restoration and balancing solve what is unknown.', influences: ['brahmagupta'] },
  { id: 'alhaytham', name: 'Ibn al-Haytham', born: 965, died: 1040, era: 'isl', school: 'Cairo', tradition: 'islam',
    blurb: 'Feigned madness to escape a caliph’s dam project, then wrote the Book of Optics under house arrest: geometry turned on light itself, hypotheses tested by experiment. Mathematics as the grammar of empirical science.',
    line: 'Doubt everything; measure what remains.', influences: ['euclid'] },
  { id: 'khayyam', name: 'Omar Khayyam', born: 1048, died: 1131, era: 'isl', school: 'Nishapur', tradition: 'islam',
    blurb: 'Solved cubic equations by intersecting circles with cones, reformed the Persian calendar to astonishing accuracy, probed Euclid’s parallel postulate — and wrote the quatrains. Poet and geometer, one temperament.',
    line: 'The moving finger writes; and, having writ, moves on.', influences: ['alkhwarizmi', 'euclid'] },

  // ---- Renaissance ----
  { id: 'fibonacci', name: 'Fibonacci', born: 1170, died: 1250, era: 'ren', school: 'Pisa', tradition: 'west',
    blurb: 'A Pisan merchant’s son schooled in Algeria, whose Liber Abaci sold Europe on the nine Indian figures and the sign 0 — and, in a rabbit puzzle, planted the sequence that keeps surfacing in spirals ever since.',
    line: 'With nine Indian figures and the sign 0, any number may be written.', influences: ['alkhwarizmi'] },
  { id: 'cardano', name: 'Cardano', born: 1501, died: 1576, era: 'ren', school: 'Milan', tradition: 'west',
    blurb: 'Physician, gambler, and scoundrel who published the cubic’s solution in Ars Magna — and, needing square roots of negatives along the way, was the first to calculate with “impossible” numbers while holding his nose.',
    line: 'Put the mental tortures aside and multiply.', influences: ['fibonacci'] },
  { id: 'viete', name: 'Viète', born: 1540, died: 1603, era: 'ren', school: 'French algebra', tradition: 'west',
    blurb: 'A lawyer and royal codebreaker who introduced letters for unknowns AND for knowns — algebra as a symbolic language rather than rhetorical recipes. Once notation can say “any equation,” mathematics can think about itself.',
    line: 'To leave no problem unsolved.', influences: ['cardano'] },
  { id: 'napier', name: 'Napier', born: 1550, died: 1617, era: 'ren', school: 'Merchiston', tradition: 'west',
    blurb: 'A Scottish laird who spent twenty years tabulating logarithms — the trick that turns multiplication into addition. Kepler’s calculations shrank from months to days; the slide rule ran engineering for 350 years.',
    line: 'Multiplication is reduced to addition.', influences: [] },

  // ---- The Scientific Revolution ----
  { id: 'galileo', name: 'Galileo', born: 1564, died: 1642, era: 'rev', school: 'Pisa & Florence', tradition: 'west',
    blurb: 'Rolled balls down ramps until the fall of a stone became a law written in number — and declared the book of nature legible only to those who read mathematics. Also noticed the squares pair off with all the numbers: infinity misbehaving.',
    line: 'The book of nature is written in the language of mathematics.', influences: ['archimedes', 'euclid'] },
  { id: 'descartes', name: 'Descartes', born: 1596, died: 1650, era: 'rev', school: 'Analytic geometry', tradition: 'west',
    blurb: 'In an appendix to a philosophy book, wedded algebra to geometry: every curve an equation, every equation a curve. The coordinate plane is the dictionary the calculus will be written in.',
    line: 'Every curve is an equation; every equation, a curve.', influences: ['viete', 'galileo'] },
  { id: 'fermat', name: 'Fermat', born: 1607, died: 1665, era: 'rev', school: 'Toulouse', tradition: 'west',
    blurb: 'A provincial magistrate who did mathematics by candlelight and letters: co-invented coordinates and probability, found tangents before calculus, and scribbled in a margin the note that took 358 years to settle.',
    line: 'I have found a truly marvelous proof, which this margin is too narrow to contain.', influences: ['viete'] },
  { id: 'pascal', name: 'Pascal', born: 1623, died: 1662, era: 'rev', school: 'Port-Royal', tradition: 'west',
    blurb: 'At sixteen a theorem on conics, at nineteen a calculating machine, at thirty-one — in letters with Fermat about a gambler’s stakes — the mathematics of chance. Then he wagered everything on God and put the dice down.',
    line: 'The eternal silence of these infinite spaces frightens me.', influences: ['fermat'] },
  { id: 'newton', name: 'Newton', born: 1643, died: 1727, era: 'rev', school: 'Cambridge', tradition: 'west',
    blurb: 'In two plague years invented fluxions, dispersed light, and began the system that made one law hold for apple and Moon alike. The Principia is Galileo’s bet paid in full: the world, derived.',
    line: 'If I have seen further, it is by standing on the shoulders of giants.', influences: ['galileo', 'descartes'] },
  { id: 'leibniz', name: 'Leibniz', born: 1646, died: 1716, era: 'rev', school: 'Hanover', tradition: 'west',
    blurb: 'Invented the calculus independently — and its notation, the dx and ∫ we still write — while dreaming bigger: a universal symbolic language in which every dispute ends with “let us calculate.” Logic machines begin here.',
    line: 'Let us calculate.', influences: ['pascal', 'descartes'] },

  // ---- The Age of Euler ----
  { id: 'euler', name: 'Euler', born: 1707, died: 1783, era: 'enl', school: 'Basel & St Petersburg', tradition: 'west',
    blurb: 'The most prolific mathematician who ever lived — half blind, then fully blind, and faster than ever. Gave us f(x), e, i, π in harness (e^iπ + 1 = 0), solved Königsberg’s bridges, and touched every field there was.',
    line: 'Nothing takes place in the world whose meaning is not that of some maximum or minimum.', influences: ['newton', 'leibniz'] },
  { id: 'laplace', name: 'Laplace', born: 1749, died: 1827, era: 'enl', school: 'Paris', tradition: 'west',
    blurb: 'Finished Newton’s solar system — proving it stable without divine adjustment — and built probability into a calculus of ignorance: a demon knowing every position and force would hold the future in one formula.',
    line: 'An intelligence knowing all forces and positions would hold the future in one formula.', influences: ['newton', 'euler'] },
  { id: 'fourier', name: 'Fourier', born: 1768, died: 1830, era: 'enl', school: 'Paris', tradition: 'west',
    blurb: 'Napoleon’s governor in Egypt, then the man who claimed any signal — any heat flow, any sound, any curve — decomposes into pure waves. The frequency domain: a second way of seeing everything that varies.',
    line: 'Mathematics compares the most diverse phenomena and discovers the secret analogies that unite them.', influences: ['euler'] },
  { id: 'germain', name: 'Sophie Germain', born: 1776, died: 1831, era: 'enl', school: 'Paris', tradition: 'west',
    blurb: 'Taught herself from her father’s library while Paris rioted, wrote to Lagrange and Gauss as “Monsieur Le Blanc,” and made the first general advance on Fermat’s Last Theorem. Gauss called her proof of courage complete.',
    line: 'Algebra is but written geometry; geometry, figured algebra.', influences: ['euler', 'gauss'] },

  // ---- The Age of Rigor ----
  { id: 'gauss', name: 'Gauss', born: 1777, died: 1855, era: 'rig', school: 'Göttingen', tradition: 'west',
    blurb: 'Summed 1 to 100 as a schoolboy in seconds, proved quadratic reciprocity at nineteen, and kept non-Euclidean geometry in a drawer for fear of the uproar. The prince of mathematicians; number theory’s modern founder.',
    line: 'Mathematics is the queen of the sciences, and arithmetic the queen of mathematics.', influences: ['euler', 'newton'] },
  { id: 'cauchy', name: 'Cauchy', born: 1789, died: 1857, era: 'rig', school: 'École Polytechnique', tradition: 'west',
    blurb: 'Took the calculus that worked and asked why it was allowed to: limits defined, convergence policed, complex analysis built. Rigor as a moral stance — prove it, or it is not yet mathematics.',
    line: 'Limits, not intuitions.', influences: ['euler'] },
  { id: 'abel', name: 'Abel', born: 1802, died: 1829, era: 'rig', school: 'Christiania', tradition: 'west',
    blurb: 'A poor Norwegian who proved the general quintic unsolvable by radicals — closing a 300-year quest — and opened elliptic functions, all before dying of tuberculosis at 26, two days before the letter offering him a job.',
    line: 'Read the masters, not the pupils.', influences: ['gauss', 'cauchy'] },
  { id: 'galois', name: 'Galois', born: 1811, died: 1832, era: 'rig', school: 'Paris', tradition: 'west',
    blurb: 'Dead in a duel at twenty, leaving papers the Academy had twice lost: solvability of equations read off from the symmetries of their roots. The group — structure itself as an object — is his monument.',
    line: 'Jump above calculations: group the operations.', influences: ['gauss', 'abel'] },
  { id: 'lobachevsky', name: 'Lobachevsky', born: 1792, died: 1856, era: 'rig', school: 'Kazan', tradition: 'west',
    blurb: 'Rector of Kazan who published what Gauss dared not: a full geometry in which parallels diverge and triangles come up short of 180°. Consistent, alien, and eventually — in relativity — physical.',
    line: 'There is no branch of mathematics which may not some day be applied to the phenomena of the real world.', influences: ['euclid', 'khayyam'] },
  { id: 'riemann', name: 'Riemann', born: 1826, died: 1866, era: 'rig', school: 'Göttingen', tradition: 'west',
    blurb: 'In one shy lecture re-founded geometry: space as a manifold whose curvature varies point to point — the mathematics general relativity would need on the shelf. His zeta hypothesis remains the deepest open question in mathematics.',
    line: 'Space is a hypothesis.', influences: ['gauss', 'cauchy'] },
  { id: 'cantor', name: 'Cantor', born: 1845, died: 1918, era: 'rig', school: 'Halle', tradition: 'west',
    blurb: 'Took Galileo’s troubling pairing and ran the other way: infinite sets can be counted against each other, and some infinities are strictly bigger. Set theory, the transfinite, and a paradise mathematics refused to leave.',
    line: 'The essence of mathematics lies in its freedom.', influences: ['galileo'] },
  { id: 'boole', name: 'Boole', born: 1815, died: 1864, era: 'rig', school: 'Cork', tradition: 'west',
    blurb: 'A self-taught cobbler’s son who wrote reasoning itself as algebra: AND, OR, NOT with laws like arithmetic’s. A curiosity for ninety years — until a century later every circuit on Earth was running his logic.',
    line: 'The laws of thought are written in symbols.', influences: ['leibniz'] },
  { id: 'kovalevskaya', name: 'Kovalevskaya', born: 1850, died: 1891, era: 'rig', school: 'Stockholm', tradition: 'west',
    blurb: 'Learned calculus from lecture notes papering her nursery wall, contracted a marriage of convenience to reach a university that would have her, and won the Prix Bordin for the spinning top. First woman to hold a modern chair in mathematics.',
    line: 'It is impossible to be a mathematician without being a poet in soul.', influences: ['cauchy'] },
  { id: 'poincare', name: 'Poincaré', born: 1854, died: 1912, era: 'rig', school: 'Paris', tradition: 'west',
    blurb: 'The last universalist. Created topology, glimpsed relativity — and, in a prize essay on three bodies, found deterministic orbits too tangled to predict: chaos, a century early. His conjecture took ninety-eight years to prove.',
    line: 'Mathematics is the art of giving the same name to different things.', influences: ['riemann', 'laplace'] },

  // ---- Crisis & Foundations ----
  { id: 'hilbert', name: 'Hilbert', born: 1862, died: 1943, era: 'fou', school: 'Göttingen', tradition: 'west',
    blurb: 'Set the twentieth century its 23 problems and its program: axiomatize everything, prove mathematics consistent by finite means. The program broke — gloriously — but the confidence built modern mathematics.',
    line: 'We must know — we will know.', influences: ['euclid', 'cantor'] },
  { id: 'noether', name: 'Emmy Noether', born: 1882, died: 1935, era: 'fou', school: 'Göttingen', tradition: 'west',
    blurb: 'Taught for years unpaid under men’s names, and reorganized algebra around structures — rings, ideals — rather than calculations. Her theorem welding symmetry to conservation is physics’ deepest single sentence.',
    line: 'Every symmetry conserves something.', influences: ['hilbert', 'galois'] },
  { id: 'ramanujan', name: 'Ramanujan', born: 1887, died: 1920, era: 'fou', school: 'Madras & Cambridge', tradition: 'india',
    blurb: 'A clerk in Madras filling notebooks with identities no one had seen, mailed them to Hardy — “they must be true, because no one would have the imagination to invent them” — and in seven English years changed number theory forever.',
    line: 'An equation for me has no meaning unless it expresses a thought of God.', influences: ['euler'] },
  { id: 'godel', name: 'Gödel', born: 1906, died: 1978, era: 'fou', school: 'Vienna & Princeton', tradition: 'west',
    blurb: 'At twenty-five proved that any consistent system rich enough for arithmetic contains truths it cannot prove — and cannot prove its own consistency. Hilbert’s program ended; mathematics learned its own horizon.',
    line: 'Truth outruns proof.', influences: ['hilbert', 'cantor', 'leibniz'] },

  // ---- The Modern Age ----
  { id: 'turing', name: 'Turing', born: 1912, died: 1954, era: 'mod', school: 'Cambridge & Bletchley', tradition: 'west',
    blurb: 'Answered Hilbert’s decision problem with an imaginary machine of tape and states — thereby defining computation itself — then built real ones against Enigma and asked whether machines can think. Persecuted to death by his own state.',
    line: 'We can only see a short distance ahead, but we can see plenty there that needs to be done.', influences: ['godel', 'hilbert'] },
  { id: 'vonneumann', name: 'von Neumann', born: 1903, died: 1957, era: 'mod', school: 'Princeton', tradition: 'west',
    blurb: 'Axiomatized set theory at 22 and quantum mechanics at 28, invented game theory, the stored-program computer, and cellular automata — machines that copy themselves. The century’s fastest mind, everywhere at once.',
    line: 'In mathematics you don’t understand things; you just get used to them.', influences: ['hilbert'] },
  { id: 'kolmogorov', name: 'Kolmogorov', born: 1903, died: 1987, era: 'mod', school: 'Moscow', tradition: 'west',
    blurb: 'Put probability on axioms in sixty pages — chance as measure — then ranged across turbulence, complexity, and dynamical systems. After him, uncertainty is not the absence of mathematics but a branch of it.',
    line: 'Probability is measure.', influences: ['cantor', 'laplace'] },
  { id: 'erdos', name: 'Erdős', born: 1913, died: 1996, era: 'mod', school: 'Itinerant', tradition: 'west',
    blurb: 'Owned a suitcase, no house, no job — arrived at colleagues’ doors announcing “my brain is open,” co-wrote 1,500 papers, and spoke of The Book in which God keeps the perfect proofs. Mathematics as a life lived jointly.',
    line: 'That proof is straight from The Book.', influences: ['euler'] },
  { id: 'shannon', name: 'Shannon', born: 1916, died: 2001, era: 'mod', school: 'Bell Labs', tradition: 'west',
    blurb: 'In a master’s thesis, showed circuits obey Boole’s algebra; in one 1948 paper, defined information, measured it in bits, and set the limits of every channel. The digital world runs inside his theorems.',
    line: 'Information is the resolution of uncertainty.', influences: ['boole', 'vonneumann'] },
  { id: 'grothendieck', name: 'Grothendieck', born: 1928, died: 2014, era: 'mod', school: 'IHÉS', tradition: 'west',
    blurb: 'Rebuilt algebraic geometry from beneath — schemes, topoi: not solving problems but dissolving them in a rising sea of the right generality. Then renounced mathematics for radical solitude in the Pyrenees.',
    line: 'The rising sea submerges the problem.', influences: ['noether', 'riemann'] },
  { id: 'mandelbrot', name: 'Mandelbrot', born: 1924, died: 2010, era: 'mod', school: 'IBM', tradition: 'west',
    blurb: 'Asked how long the coast of Britain is and answered: it depends how closely you look. Fractals — self-similar roughness, dimension in fractions — gave nature’s irregularity its geometry, drawn on IBM’s printers.',
    line: 'Clouds are not spheres, mountains are not cones, coastlines are not circles.', influences: ['poincare'] },
  { id: 'conway', name: 'Conway', born: 1937, died: 2020, era: 'mod', school: 'Cambridge & Princeton', tradition: 'west',
    blurb: 'Played games so seriously they became mathematics: the Game of Life, where three rules breed gliders, growth, and universal computation — and the surreal numbers, an arithmetic containing every infinity and infinitesimal, found inside Go endgames.',
    line: 'From three rules, a universe.', influences: ['vonneumann', 'cantor'] },
  { id: 'wiles', name: 'Wiles', born: 1953, died: null, era: 'mod', school: 'Princeton & Oxford', tradition: 'west',
    blurb: 'Read about Fermat’s margin at ten, worked seven years in secret in an attic, and in 1993 ended a 358-year-old story — then spent a harrowing year repairing the gap. Proof as a life’s quiet, total commitment.',
    line: 'I think I’ll stop here.', influences: ['fermat', 'germain'] },
  { id: 'mirzakhani', name: 'Mirzakhani', born: 1977, died: 2017, era: 'mod', school: 'Tehran & Stanford', tradition: 'west',
    blurb: 'Drew on huge sheets of paper on the floor — “like painting,” her daughter said — while counting geodesics on curved surfaces and the moduli of all possible geometries. First woman awarded the Fields Medal; gone at forty.',
    line: 'The beauty of mathematics only shows itself to more patient followers.', influences: ['riemann'] },
]

// Birthplaces (approximate town coordinates) for the globe view.
const PLACES = {
  ahmes: { name: 'Thebes', lat: 25.7, lon: 32.64 },
  thales: { name: 'Miletus', lat: 37.53, lon: 27.28 },
  pythagoras: { name: 'Samos', lat: 37.75, lon: 26.83 },
  zeno: { name: 'Elea', lat: 40.16, lon: 15.15 },
  euclid: { name: 'Alexandria', lat: 31.2, lon: 29.92 },
  archimedes: { name: 'Syracuse', lat: 37.08, lon: 15.29 },
  eratosthenes: { name: 'Cyrene', lat: 32.82, lon: 21.86 },
  hypatia: { name: 'Alexandria', lat: 31.2, lon: 29.92 },
  liuhui: { name: 'Zibo, Shandong', lat: 36.8, lon: 118.05 },
  aryabhata: { name: 'Kusumapura (Patna)', lat: 25.61, lon: 85.14 },
  brahmagupta: { name: 'Bhillamala (Bhinmal)', lat: 25.0, lon: 72.25 },
  madhava: { name: 'Sangamagrama, Kerala', lat: 10.34, lon: 76.21 },
  alkhwarizmi: { name: 'Khwarazm (Khiva)', lat: 41.38, lon: 60.36 },
  alhaytham: { name: 'Basra', lat: 30.51, lon: 47.81 },
  khayyam: { name: 'Nishapur', lat: 36.21, lon: 58.8 },
  fibonacci: { name: 'Pisa', lat: 43.72, lon: 10.4 },
  cardano: { name: 'Pavia', lat: 45.19, lon: 9.16 },
  viete: { name: 'Fontenay-le-Comte', lat: 46.47, lon: -0.8 },
  napier: { name: 'Merchiston, Edinburgh', lat: 55.93, lon: -3.21 },
  galileo: { name: 'Pisa', lat: 43.72, lon: 10.4 },
  descartes: { name: 'La Haye, Touraine', lat: 46.99, lon: 0.7 },
  fermat: { name: 'Beaumont-de-Lomagne', lat: 43.88, lon: 0.99 },
  pascal: { name: 'Clermont-Ferrand', lat: 45.78, lon: 3.08 },
  newton: { name: 'Woolsthorpe', lat: 52.81, lon: -0.63 },
  leibniz: { name: 'Leipzig', lat: 51.34, lon: 12.37 },
  euler: { name: 'Basel', lat: 47.56, lon: 7.59 },
  laplace: { name: 'Beaumont-en-Auge', lat: 49.28, lon: 0.11 },
  fourier: { name: 'Auxerre', lat: 47.8, lon: 3.57 },
  germain: { name: 'Paris', lat: 48.86, lon: 2.35 },
  gauss: { name: 'Brunswick', lat: 52.27, lon: 10.52 },
  cauchy: { name: 'Paris', lat: 48.86, lon: 2.35 },
  abel: { name: 'Nedstrand, Norway', lat: 59.35, lon: 5.84 },
  galois: { name: 'Bourg-la-Reine', lat: 48.78, lon: 2.32 },
  lobachevsky: { name: 'Nizhny Novgorod', lat: 56.33, lon: 44.0 },
  riemann: { name: 'Breselenz', lat: 53.1, lon: 11.03 },
  cantor: { name: 'St Petersburg', lat: 59.94, lon: 30.31 },
  boole: { name: 'Lincoln', lat: 53.23, lon: -0.54 },
  kovalevskaya: { name: 'Moscow', lat: 55.76, lon: 37.62 },
  poincare: { name: 'Nancy', lat: 48.69, lon: 6.18 },
  hilbert: { name: 'Königsberg', lat: 54.71, lon: 20.51 },
  noether: { name: 'Erlangen', lat: 49.6, lon: 11.0 },
  ramanujan: { name: 'Erode', lat: 11.34, lon: 77.72 },
  godel: { name: 'Brünn (Brno)', lat: 49.2, lon: 16.61 },
  turing: { name: 'London', lat: 51.53, lon: -0.19 },
  vonneumann: { name: 'Budapest', lat: 47.5, lon: 19.04 },
  kolmogorov: { name: 'Tambov', lat: 52.72, lon: 41.45 },
  erdos: { name: 'Budapest', lat: 47.5, lon: 19.04 },
  shannon: { name: 'Petoskey, Michigan', lat: 45.37, lon: -84.96 },
  grothendieck: { name: 'Berlin', lat: 52.52, lon: 13.41 },
  mandelbrot: { name: 'Warsaw', lat: 52.23, lon: 21.01 },
  conway: { name: 'Liverpool', lat: 53.41, lon: -2.98 },
  wiles: { name: 'Cambridge', lat: 52.21, lon: 0.12 },
  mirzakhani: { name: 'Tehran', lat: 35.69, lon: 51.39 },
}

// Further-reading targets: MacTutor biography slug and Wikipedia title.
// (MacTutor is to mathematicians what the SEP is to philosophers.)
const LINKS = {
  ahmes: { mac: 'Ahmes', wiki: 'Ahmes' },
  thales: { mac: 'Thales', wiki: 'Thales_of_Miletus' },
  pythagoras: { mac: 'Pythagoras', wiki: 'Pythagoras' },
  zeno: { mac: 'Zeno_of_Elea', wiki: 'Zeno_of_Elea' },
  euclid: { mac: 'Euclid', wiki: 'Euclid' },
  archimedes: { mac: 'Archimedes', wiki: 'Archimedes' },
  eratosthenes: { mac: 'Eratosthenes', wiki: 'Eratosthenes' },
  hypatia: { mac: 'Hypatia', wiki: 'Hypatia' },
  liuhui: { mac: 'Liu_Hui', wiki: 'Liu_Hui' },
  aryabhata: { mac: 'Aryabhata_I', wiki: 'Aryabhata' },
  brahmagupta: { mac: 'Brahmagupta', wiki: 'Brahmagupta' },
  madhava: { mac: 'Madhava', wiki: 'Madhava_of_Sangamagrama' },
  alkhwarizmi: { mac: 'Al-Khwarizmi', wiki: 'Al-Khwarizmi' },
  alhaytham: { mac: 'Al-Haytham', wiki: 'Ibn_al-Haytham' },
  khayyam: { mac: 'Khayyam', wiki: 'Omar_Khayyam' },
  fibonacci: { mac: 'Fibonacci', wiki: 'Fibonacci' },
  cardano: { mac: 'Cardan', wiki: 'Gerolamo_Cardano' },
  viete: { mac: 'Viete', wiki: 'Francois_Viete' },
  napier: { mac: 'Napier', wiki: 'John_Napier' },
  galileo: { mac: 'Galileo', wiki: 'Galileo_Galilei' },
  descartes: { mac: 'Descartes', wiki: 'Rene_Descartes' },
  fermat: { mac: 'Fermat', wiki: 'Pierre_de_Fermat' },
  pascal: { mac: 'Pascal', wiki: 'Blaise_Pascal' },
  newton: { mac: 'Newton', wiki: 'Isaac_Newton' },
  leibniz: { mac: 'Leibniz', wiki: 'Gottfried_Wilhelm_Leibniz' },
  euler: { mac: 'Euler', wiki: 'Leonhard_Euler' },
  laplace: { mac: 'Laplace', wiki: 'Pierre-Simon_Laplace' },
  fourier: { mac: 'Fourier', wiki: 'Joseph_Fourier' },
  germain: { mac: 'Germain', wiki: 'Sophie_Germain' },
  gauss: { mac: 'Gauss', wiki: 'Carl_Friedrich_Gauss' },
  cauchy: { mac: 'Cauchy', wiki: 'Augustin-Louis_Cauchy' },
  abel: { mac: 'Abel', wiki: 'Niels_Henrik_Abel' },
  galois: { mac: 'Galois', wiki: 'Evariste_Galois' },
  lobachevsky: { mac: 'Lobachevsky', wiki: 'Nikolai_Lobachevsky' },
  riemann: { mac: 'Riemann', wiki: 'Bernhard_Riemann' },
  cantor: { mac: 'Cantor', wiki: 'Georg_Cantor' },
  boole: { mac: 'Boole', wiki: 'George_Boole' },
  kovalevskaya: { mac: 'Kovalevskaya', wiki: 'Sofya_Kovalevskaya' },
  poincare: { mac: 'Poincare', wiki: 'Henri_Poincare' },
  hilbert: { mac: 'Hilbert', wiki: 'David_Hilbert' },
  noether: { mac: 'Noether_Emmy', wiki: 'Emmy_Noether' },
  ramanujan: { mac: 'Ramanujan', wiki: 'Srinivasa_Ramanujan' },
  godel: { mac: 'Godel', wiki: 'Kurt_Godel' },
  turing: { mac: 'Turing', wiki: 'Alan_Turing' },
  vonneumann: { mac: 'Von_Neumann', wiki: 'John_von_Neumann' },
  kolmogorov: { mac: 'Kolmogorov', wiki: 'Andrey_Kolmogorov' },
  erdos: { mac: 'Erdos', wiki: 'Paul_Erdos' },
  shannon: { mac: 'Shannon', wiki: 'Claude_Shannon' },
  grothendieck: { mac: 'Grothendieck', wiki: 'Alexander_Grothendieck' },
  mandelbrot: { mac: 'Mandelbrot', wiki: 'Benoit_Mandelbrot' },
  conway: { mac: 'Conway', wiki: 'John_Horton_Conway' },
  wiles: { mac: 'Wiles', wiki: 'Andrew_Wiles' },
  mirzakhani: { mac: 'Mirzakhani', wiki: 'Maryam_Mirzakhani' },
}

export const MATHEMATICIANS = ROSTER.map(p => ({
  ...p,
  ...(DETAILS[p.id] ?? {}),
  portrait: `portraits/${p.id}.jpg`,
  thumb: `portraits/thumbs/${p.id}.png`,
  place: PLACES[p.id],
  alias: LINKS[p.id].wiki.replaceAll('_', ' '),
  influenced: ROSTER.filter(q => q.influences.includes(p.id)).map(q => q.id),
  links: [
    { label: 'MacTutor', url: `https://mathshistory.st-andrews.ac.uk/Biographies/${LINKS[p.id].mac}/` },
    { label: 'Wikipedia', url: `https://en.wikipedia.org/wiki/${LINKS[p.id].wiki}` },
  ],
}))

export const byId = Object.fromEntries(MATHEMATICIANS.map(p => [p.id, p]))
export const eraById = Object.fromEntries(ERAS.map(e => [e.id, e]))
