// One line on what actually passed along each influence edge, keyed 'from>to'.
// A test asserts every influences[] pair in the data has an entry here.
// Edges marked by sense: some are direct transmission (teacher, translation,
// documented reading), some conceptual descent — the text says which.
export const EDGES = {
  'ahmes>thales': 'Tradition says Thales learned geometry in Egypt — the recipes he received, he returned as theorems.',
  'thales>pythagoras': 'The elder sage reportedly urged him to study in Egypt; proof passed from the first hand to the second.',
  'pythagoras>euclid': 'Pythagorean number lore and geometry, sifted and systematized into the Elements’ deductive order.',
  'euclid>archimedes': 'The Elements is the platform; Archimedes stands on its rigor to weigh what Euclid never dared.',
  'euclid>eratosthenes': 'Alexandrian geometry applied outward — proportion and angle turned on the Earth itself.',
  'euclid>hypatia': 'She taught and preserved the Euclidean tradition as its living voice in a dying Alexandria.',
  'aryabhata>brahmagupta': 'The Aryabhatiya’s place-value astronomy set the agenda Ujjain’s master extended to zero and debts.',
  'brahmagupta>madhava': 'The Siddhanta tradition of Indian astronomy, carried south to Kerala and pushed to the infinite.',
  'brahmagupta>alkhwarizmi': 'The Sindhind brought to Baghdad was Brahmagupta’s text — Indian arithmetic translated into Arabic science.',
  'euclid>alhaytham': 'Optics is geometry turned on light — Euclid’s lines and angles, aimed through the camera obscura.',
  'alkhwarizmi>khayyam': 'Al-jabr inherited and pushed past the quadratic — to the cubics algebra alone could not yet crack.',
  'euclid>khayyam': 'His commentary probed the parallel postulate’s weakness — loyalty to Euclid, sharpened into doubt.',
  'alkhwarizmi>fibonacci': 'Liber Abaci carries al-Khwarizmi’s arithmetic and algebra — by name — from Béjaïa into Latin Europe.',
  'fibonacci>cardano': 'The Italian abacus tradition Liber Abaci founded fed the algebraists of Bologna and Milan.',
  'cardano>viete': 'Ars Magna’s solutions in rhetorical prose — Viète gave that power a symbolic language.',
  'archimedes>galileo': 'His declared master: statics, centers of gravity, and the nerve to mathematize the physical.',
  'euclid>galileo': 'Proportion theory from the Elements is the grammar of the Two New Sciences’ laws of motion.',
  'viete>descartes': 'Symbolic algebra inherited (and its notation improved) — the letters La Géométrie computes with.',
  'galileo>descartes': 'The mathematization of nature as program — Descartes supplied the geometry to write it in.',
  'viete>fermat': 'Fermat learned analysis restoring Apollonius by Viète’s methods; the symbolism became his instrument.',
  'fermat>pascal': 'The 1654 letters on the gambler’s stakes — expectation worked out between the two of them.',
  'galileo>newton': 'The law of fall and the inertial road; Newton begins where the Two New Sciences stops.',
  'descartes>newton': 'Newton mastered La Géométrie before all else — coordinates are the stage of the Principia’s analysis.',
  'pascal>leibniz': 'Reading Pascal’s triangle papers in Paris sparked the characteristic triangle — calculus’s seed.',
  'descartes>leibniz': 'The curve-equation dictionary that differentials were invented to read infinitesimally.',
  'newton>euler': 'Newtonian mechanics, rewritten in analysis — Euler made the Principia differential.',
  'leibniz>euler': 'Through the Bernoullis, Leibniz’s calculus and notation — the dialect Euler made universal.',
  'newton>laplace': 'The System of the World, finished: perturbations resolved, stability proved, God unemployed.',
  'euler>laplace': 'Eulerian analysis — generating functions, mechanics — the toolkit of celestial mechanics.',
  'euler>fourier': 'Trigonometric series Euler had handled formally, Fourier claimed for every function.',
  'euler>germain': 'Her number theory grew from Euler’s Fermat proofs — the n=3 case showed the path to attack.',
  'gauss>germain': 'The Disquisitiones was her closest companion; their correspondence tested her theorems against its author.',
  'euler>gauss': 'Euler’s number theory, scattered in papers, became the Disquisitiones’ organized kingdom.',
  'newton>gauss': 'The Principia’s standard of proof — Gauss ranked Newton above all and orbit-hunted like him.',
  'euler>cauchy': 'The vast analysis Euler used freely is exactly what Cauchy resolved to make rigorous.',
  'gauss>abel': 'The Disquisitiones’ cyclotomy showed which equations do yield — the map for proving which don’t.',
  'cauchy>abel': 'Cauchy’s rigor became Abel’s creed — his binomial series paper out-Cauchys Cauchy.',
  'gauss>galois': 'Cyclotomic solvability in the Disquisitiones — the worked example Galois generalized to all equations.',
  'abel>galois': 'Abel proved the quintic impossible; Galois explained which equations are, and why.',
  'euclid>lobachevsky': 'Two millennia of loyalty to the fifth postulate — ended by taking Euclid seriously enough to vary him.',
  'khayyam>lobachevsky': 'Conceptual descent: the quadrilateral Khayyam probed became the doorway Lobachevsky walked through.',
  'gauss>riemann': 'Doctoral teacher; the Theorema Egregium’s intrinsic curvature, generalized to n dimensions.',
  'cauchy>riemann': 'Complex analysis received and transformed — Cauchy’s integrals become Riemann’s surfaces.',
  'galileo>cantor': 'Conceptual descent: the paradox of the squares, which Galileo shelved and Cantor made the definition of infinite.',
  'leibniz>boole': 'The calculus ratiocinator — reasoning as computation — delivered as working algebra.',
  'cauchy>kovalevskaya': 'His existence theorem for differential equations is the one her name now completes.',
  'riemann>poincare': 'Riemann surfaces and manifolds — the geometric imagination Analysis Situs made topological.',
  'laplace>poincare': 'Celestial mechanics inherited — and its confident determinism found chaotic at the third body.',
  'euclid>hilbert': 'The Grundlagen re-axiomatized Euclid’s geometry — gaps closed, axioms made a formal science.',
  'cantor>hilbert': 'The transfinite paradise Hilbert vowed no one would expel mathematics from.',
  'hilbert>noether': 'Brought her to Göttingen over the faculty’s objections; his invariant problems, her theorem.',
  'galois>noether': 'Group-theoretic structure as the object of study — extended from equations to all of algebra.',
  'euler>ramanujan': 'His closest kin in style: series, products, continued fractions — Hardy said only Euler compared.',
  'hilbert>godel': 'The program to prove mathematics consistent — answered, exactly and in the negative.',
  'cantor>godel': 'Set theory and the diagonal method — the loop incompleteness runs through arithmetic.',
  'leibniz>godel': 'Gödel’s declared philosophical master — the characteristica universalis, tested to its limit.',
  'godel>turing': 'Incompleteness recast as computation: what proof cannot reach, no machine can decide.',
  'hilbert>turing': 'The Entscheidungsproblem, posed by Hilbert’s school — answered by inventing the computer.',
  'hilbert>vonneumann': 'Hilbert’s axiomatic program, executed on sets and on quantum mechanics by his fastest disciple.',
  'cantor>kolmogorov': 'Set theory and measure — the raw material of the 1933 axioms of probability.',
  'laplace>kolmogorov': 'The classical calculus of chance, refounded on measure so its paradoxes dissolve.',
  'euler>erdos': 'Elementary number theory in the Eulerian spirit — proofs from first principles, endlessly inventive.',
  'boole>shannon': 'The master’s thesis: relay circuits obey the algebra of logic — Boole, electrified.',
  'vonneumann>shannon': 'Advised him (so the story goes) to call it entropy — “no one knows what entropy really is.”',
  'noether>grothendieck': 'Her abstract algebra — rings, ideals, modules — is the language schemes are written in.',
  'riemann>grothendieck': 'Riemann surfaces and the Riemann–Roch theorem — the geometry EGA rebuilt in full generality.',
  'poincare>mandelbrot': 'Iteration and dynamical systems — the seed (via Julia and Fatou) of the set that filled the screen.',
  'vonneumann>conway': 'Self-reproducing automata, 29 states — Conway’s Life got it down to three rules on a Go board.',
  'cantor>conway': 'Transfinite construction by stages — the surreals extend Cantor’s ordinals into a number field.',
  'fermat>wiles': 'The margin note itself — read at ten, carried for thirty years, closed at last.',
  'germain>wiles': 'Conceptual descent: her strategy of attacking infinitely many exponents at once, fulfilled by modularity.',
  'riemann>mirzakhani': 'Riemann surfaces and their moduli — literally the space her theorems measure.',
}
